### ISSUE TITLE
dhewm3 does not start in a wayland session

### ISSUE THREAD

**Issue by obedlink** [dhewm/dhewm3#425] opened 2021-11-19 01:39 UTC
dhewm3 is not that it does not work in wayland.
dhewm3 has been working in wayland for years, but the executable does not detect what type of session it is running in.
for the executable to run in wayland you have to run it as follows:

$ SDL_VIDEODRIVER=wayland ./dhewm3

This is not a bug report, it is a request.
make the executable or SDL  detect what type of session is being used if, x11 or wayland and make its modifications to run.

this to make life easier for users.
greetings and congratulations for this great project

**Comment by DanielGibson** [comment] 2021-11-19 02:01
I'm glad to hear dhewm3 (mostly) works on wayland!

To be honest this sounds more like an SDL bug than a dhewm3 bug.

I know that there have been lots of wayland-specific improvements to SDL since the last release - you could try building the latest SDL source from git: https://github.com/libsdl-org/SDL/

**Comment by obedlink** [comment] 2021-11-19 17:50
> I'm glad to hear dhewm3 (mostly) works on wayland!
> 
> To be honest this sounds more like an SDL bug than a dhewm3 bug.
> 
> I know that there have been lots of wayland-specific improvements to SDL since its last release (2.0.16) - you could try building the latest SDL source from git: https://github.com/libsdl-org/SDL/

I have compiled and used the latest version (2.0.16) of SDL2 with the same result. but i found the bug

the game runs perfectly on wayland executing the command
"$ ./dhewm3"

You can configure any graphic quality and resolution and AA 2x, 4x.
but when using 8x, when applying changes and restarting the game it gets stuck in:

----- Initializing OpenGL -----
Initializing OpenGL subsystem

but if I run it using the command:
"$ SDL_VIDEODRIVER = wayland ./dhewm3"

the game starts smoothly with 8x AA.

**Comment by DanielGibson** [comment] 2021-11-19 17:58
I would have thought that SDL automatically uses wayland if you're on Wayland (otherwise I assume it runs through xwayland - no idea why that makes 8x AA fail) - but I don't know, I don't use wayland myself (because I like XFCE too much)

**Comment by DanielGibson** [comment] 2021-11-19 18:01
Oh, also, don't use the latest version (2.0.16) of SDL, but compile the latest **SDL2 code from git** - the recent wayland changes haven't been in a formal release yet

**Comment by obedlink** [comment] 2021-11-19 18:02
> I would have thought that SDL automatically uses wayland if you're on Wayland (otherwise I assume it runs through xwayland - no idea why that makes 8x AA fail) - but I don't know, I don't use wayland myself (because I like XFCE too much)
> 
> Also, which GPU and driver and what desktop environment and Linux distro etc are you using?

I'm using KDE-Neon, Radeon driver, Mesa 21.3.
I will try with SDL2 git

**Comment by DanielGibson** [comment] 2021-11-20 16:03
Does it work with SDL2 git?
Otherwise we should file a bugreport there, so it hopefully gets fixed before they release 2.0.18 (which is supposed to be soon)

**Comment by obedlink** [comment] 2021-11-21 00:52
> Does it work with SDL2 git? Otherwise we should file a bugreport there, so it hopefully gets fixed before they release 2.0.18 (which is supposed to happen soon)

I compile SDL2 git but the bug remains.
configuring 8x AA within the game, the next boot it hangs initializing the OpenGL Subsystem

**Comment by DanielGibson** [comment] 2021-11-21 02:15
I just pushed a commit that prints the SDL video driver at startup, can you build dhewm3 from its latest git code and post dhewm3's console output **both** with and without `SDL_VIDEODRIVER=wayland`?

**Comment by DanielGibson** [comment] 2021-11-21 18:01
See https://github.com/dhewm/dhewm3/issues/421#issuecomment-974864777 for how to tell dhewm3 to use the SDL2 you compiled yourself (note that the first line dhewm3 prints to the console should contain the SDL2 version which should be 2.0.17)

**Comment by DanielGibson** [comment] 2021-11-21 19:01
Ok, turns out this is intentional because SDL is still waiting for a Wayland extension to be finalized until the SDL wayland backend works well enought to replace the X11 backend.

So for now you need to explicitly use `SDL_VIDEODRIVER=wayland` to get the native backend (and working 8x AA apparently, though I have no idea why it fails on your system; @Yamagi told me it works on his gnome-based system, also when using xwayland)

**Comment by obedlink** [comment] 2021-11-21 23:47
> I just pushed a commit that prints the SDL video driver at startup, can you build dhewm3 from its latest git code and post dhewm3's console output **both** with and without `SDL_VIDEODRIVER=wayland`? (if that output gets long-ish, put it in .txt files and attach them to the post)

I have compiled dhwem3 from git and when I start the game it says that SDL is using the X11 driver.

within the game I configure everything to the maximum, resolution 4K and 8x AA, close and restart. now the SDL message keeps saying that the X11 driver is in use, but in the OpenGL part this appears.

----- Initializing OpenGL -----
Initializing OpenGL subsystem
WARNING: Not usable GL mode found: Couldn't find matching GLX visual

Unlike the stable version, the game does start, but in windowed mode and minimum resolution.

I have not tried with SDL git, because I only compiled the binary and put it in the "libs" folder but the executables of the git version of dhwem3 do not read that folder, I don't know if any parameter should be set when compiling.

[dhwem3 no 8x AA.txt](https://github.com/dhewm/dhewm3/files/7577386/dhwem3.no.8x.AA.txt)
[dhwem3 sdl command.txt](https://github.com/dhewm/dhewm3/files/7577387/dhwem3.sdl.command.txt)
[dhwem3 with 8x AA.txt](https://github.com/dhewm/dhewm3/files/7577389/dhwem3.with.8x.AA.txt)

**Comment by DanielGibson** [comment] 2021-11-22 00:08
Thanks!

> Unlike the stable version, the game does start, but in windowed mode and minimum resolution.

Good, that's the expected/wanted behavior if no suitable window can be created due to some graphics setting (no idea why setting 8x AA fails, but this most probably is a bug in xwayland or maybe the gpu driver).

I most probably fixed the hang with https://github.com/dhewm/dhewm3/commit/52ea5b3877d676f3a9b1efa3985fd1664e6bb535 - I thought that was before 1.5.1, but I misremembered.

> I have not tried with SDL git, because I only compiled the binary and put it in the "libs" folder but the executables of the git version of dhwem3 do not read that folder

Seems like that folder doesn't work anymore (dhewm3 was supposed have RPATH $ORIGIN/libs/ set, and I'm pretty sure this used to work at some point - probably CMake broke something in newer versions).
However, it's pretty easy to tell dhewm3 to use the custom `libSDL2-2.0.so.0`, by setting the LD_LIBRARY_PATH environment variable:

> Building SDL2 should have created a libSDL2-2.0.so.0.17.0 and a libSDL2-2.0.so.0 that's a symlink to the former.
> You can tell dhewm3 to use that lib by telling it to look in the directory that contains libSDL2-2.0.so.0 with 
> `LD_LIBRARY_PATH=/path/to/that/dir/ ./dhewm3`

in your case (if you've already copied the lib into the libs/ dir next to the dhewm3 executable) it might be as easy as `LD_LIBRARY_PATH=./libs/ ./dhewm3`

If you're really lucky this fixes your issue if xwayland is used (in case it was caused by SDL and not xwayland), but as I wrote above, SDL2 will default to x11 (and thus xwayland when using wayland) until some wayland extension they're need is available.

**Comment by obedlink** [comment] 2021-11-22 01:04
> LD_LIBRARY_PATH=./libs/ ./dhewm3




> Thanks!
> 
> > Unlike the stable version, the game does start, but in windowed mode and minimum resolution.
> 
> Good, that's the expected/wanted behavior if no suitable window can be created due to some graphics setting (no idea why setting 8x AA fails, but this most probably is a bug in xwayland or maybe the gpu driver).
> 
> I most probably fixed the hang with [52ea5b3](https://github.com/dhewm/dhewm3/commit/52ea5b3877d676f3a9b1efa3985fd1664e6bb535) - I thought that was before 1.5.1, but I misremembered.
> 
> > I have not tried with SDL git, because I only compiled the binary and put it in the "libs" folder but the executables of the git version of dhwem3 do not read that folder
> 
> Seems like that folder doesn't work anymore (dhewm3 was supposed have RPATH $ORIGIN/libs/ set, and I'm pretty sure this used to work at some point - probably CMake broke something in newer versions). However, it's pretty easy to tell dhewm3 to use the custom `libSDL2-2.0.so.0`, by setting the LD_LIBRARY_PATH environment variable:
> 
> > Building SDL2 should have created a libSDL2-2.0.so.0.17.0 and a libSDL2-2.0.so.0 that's a symlink to the former.
> > You can tell dhewm3 to use that lib by telling it to look in the directory that contains libSDL2-2.0.so.0 with
> > `LD_LIBRARY_PATH=/path/to/that/dir/ ./dhewm3`
> 
> in your case (if you've already copied the lib into the libs/ dir next to the dhewm3 executable) it might be as easy as `LD_LIBRARY_PATH=./libs/ ./dhewm3`
> 
> If you're really lucky this fixes your issue if xwayland is used (in case it was caused by SDL and not xwayland), but as I wrote above, SDL2 will default to x11 (and thus xwayland when using wayland) until some wayland extension they're need is available.

Thank you!
LD_LIBRARY_PATH =. / Libs / ./dhewm3

the command ran the game using SDL2 git that I compiled, but the result is the same with 8x AA.

SDL driver: X11
----- Initializing OpenGL -----
Initializing OpenGL subsystem
WARNING: Not usable GL mode found: Couldn't find matching GLX visual

**Comment by DanielGibson** [comment] 2022-02-06 01:27
Try latest git; if this still doesn't work please post the whole dhewm3log.txt, it's in `$HOME/.local/share/dhewm3/`

Also, try SDL2 2.0.20 or newer and try forcing SDL2 to use wayland by setting the `SDL_VIDEODRIVER=wayland` environment variable.

**Comment by DanielGibson** [comment] 2022-05-16 03:04
> Seems like that folder doesn't work anymore (dhewm3 was supposed have RPATH $ORIGIN/libs/ set, and I'm pretty sure this used to work at some point - probably CMake broke something in newer versions).

This still seems to work, but requires to set the LINUX_RELEASE_BINS CMake option.

I'm closing this as this (8x AA not working) apparently isn't really a dhewm3 bug but one in wayland or your GPU drivers or whatever.

**Closed by DanielGibson** 2022-05-16 03:04 UTC
