### ISSUE TITLE
No monsters in multiplayer on client

### ISSUE THREAD

**Issue by tyabus** [dhewm/dhewm3#345] opened 2021-02-04 05:10 UTC
Is this netcode problem (or npc sync wasn't implemented at all) or it's just happens for me?
Gamedata was obtained from steam
Dhewm3 1.5.1rc2
Gentoo Linux 2.8

**Comment by HarrievG** [comment] 2021-02-07 20:27
what mp map did you run?

**Comment by DanielGibson** [comment] 2021-02-07 20:30
Is multiplayer supposed to have monsters?
Doom3 doesn't have a coop mode (without mods; see https://github.com/Stradex/librecoop), so I wouldn't expect monsters to work (I don't think I ever tried multiplayer with singleplayer maps, only with the official deathmatch maps which don't have any monsters)

**Comment by HarrievG** [comment] 2021-02-07 21:20
If you are looking for botfights:

https://github.com/jswigart/omni-bot

This actually is a fun mod to support in Dhewm3.

**Comment by tyabus** [comment] 2021-02-10 05:18
> what mp map did you run?

Net_AllowCheats 1, g_spawn (any_monster_here)
Server sees it, but client isn't

**Comment by tyabus** [comment] 2021-02-10 05:53
If you want to see it by yourself, take a look: https://youtu.be/UbM1jxX59pE

**Comment by HarrievG** [comment] 2021-02-10 08:49
Yes, I don't believe using that will work out of the box.

Unfortunately it's like Daniel said.
You can try to use the mod I linked, or you can go into the code and create
your own mod which supports it.

**Comment by HarrievG** [comment] 2021-02-10 09:00
This also seems to be a good source:

https://www.moddb.com/mods/mars-city-security/news/mars-city-security-version-build-1238-public-release

But again, I don't think we can do lot for you here. There a lot of resources on how-to do it. 

So if you are a bit code savvy, I would recommend you download Dhewm3 , build it, and make/try some stuff. The code base is incredibly clean and well documented. It is a great place to start with game development.

**Comment by HarrievG** [comment] 2021-02-13 07:53
And finally I want to share:
https://www.moddb.com/mods/opencoop

@DanielGibson it seems libre-coop is not working anymore.
OpenCoop is confirmed to work.
 https://www.reddit.com/r/Doom/comments/k5p7p9/how_do_i_get_librecoop_working/?utm_medium=android_app&utm_source=share

**Comment by DanielGibson** [comment] 2021-02-13 17:51
OpenCoop can't work with dhewm3, it doesn't have a game.dll for it

No idea why LibreCoop is supposed to be broken now, but I'm sure that can be fixed

**Comment by HarrievG** [comment] 2021-02-13 18:21
Yeah, that probably is the case.

LibreCoop sounds like fun thing to fix.
Might also be a good target to use for me, to test the debugger a bit in mod Land.

But I am not sure how what the priority of this is. 

I guess I can pick this up after the next release?

**Comment by DanielGibson** [comment] 2021-02-13 18:34
I hope to release 1.5.1 RC3 this weekend with a fix for that delta1 bug (I hope I find out what causes it tonight).
Having working LibreCoop before the final 1.5.1 release would be pretty cool of course, but that doesn't mean you have to work on it now.
Of course, you could try if you can get it running from the librecoop repo (maybe that reddit user just did something wrong); otherwise, maybe @Stradex has an idea what's going wrong. Seems like he's actively working on librecoop, last commit in https://github.com/Stradex/librecoop was an hour ago.

**Comment by HarrievG** [comment] 2021-02-13 19:21
Ill try it out this evening.
With an submit made an hour ago, It probably works out of the box..

**Comment by DanielGibson** [comment] 2021-02-13 19:39
One thing that LibreCoop (or the upcoming LibreCoop section on https://dhewm3.org/mods.html) could need is instructions on how to set it up - as far as I understand, it needs OpenCoop gamedata, so documenting what data needs to go where (and where to get that data) might be very helpful.

**Comment by HarrievG** [comment] 2021-02-13 22:56
At master with some minimal fixes to some debug prints it compiled fine. Have not ran it yet. Maybe tomorrow.

**Comment by Stradex** [comment] 2021-02-14 17:31
Hello there. I tested Librecoop with dhewm3 1.5.1 RC2 and it seems to be working fine _(I mean obviously "fine" for what an alpha mod is)_  but aside from that it works equal (and actually even better) than with dhewm3 1.5.0.
I am not sure actually what the problem is here, monsters should work fine with LibreCoop. 

I actually was playing the whole campaign with a friend these days in order to test it, we fixed some stuff from alpha 1.1 and I hope to release a new version soon. 

And about how to host it, librecoop alpha 1.1 already includes a bat that allows you to set a server automatically but to help here, you need the following things:

For Coop game mode (infinite lives): **si_gameType Coop**
For Survival game mode (limited amount of lives set by si_lives): **si_gameType Survival**
In order to play the whole campaign you are going to need the OpenCoop maps that were modified to work correctly in coop, and here they are: [https://www.moddb.com/mods/librecoop-dhewm3-coop/addons/opencoop-maps-for-librecoop1](url)

**There are extra CVARS to play with like:**

net_clientsideMovement 0/1 _(default 1)_
si_onepickupperplayer 0/1 _(default 1, each pickup item is individual for each player so two or more players can pickup the same medkit for example)_
g_unblockPlayers 0/1 _(default 0, if set to 1 players don't collide with each other):_  

**CVARs to be implemented in the new version _(not released yet)_**

g_fastMonsters 0/1 _(default 0)_
g_damageFactor _(default 1.0, the scale of damage received by the player in coop)_
g_clientsideDamage 0/1 _(default 0, if set to 1, it allows clients to deal and do damage totally clientside for a more smooth and less laggy experience. Experimental though)_

**Comment by Stradex** [comment] 2021-02-14 17:41
> And finally I want to share:
> https://www.moddb.com/mods/opencoop
> 
> @DanielGibson it seems libre-coop is not working anymore.
> OpenCoop is confirmed to work.
> https://www.reddit.com/r/Doom/comments/k5p7p9/how_do_i_get_librecoop_working/?utm_medium=android_app&utm_source=share

I saw that reddit message, and the problem seems more related to not being able to see a server using hamachi over actually Librecoop. Ideally you need to open ports in your modem/router _(27666 and 27650)_, and if still you can't see the server you can try to connect online using the console command **connect ip** _(example **connect 192.168.0.25** for LAN or **connect 186.23.123.127** for Internet)_

_"...but my buddy can't see it on LAN or internet. I might add that we are both connected to the same Hamachi network in the background. I do know how to port forward and have done it before, but I'm at a loss on how to do it with this specific mod/game..."_

**Comment by DanielGibson** [comment] 2021-02-15 17:41
Thanks a lot for the explanations, @Stradex!

It's surprising that for the reddit user OpenCoop seems to work while LibreCoop with dhewm3 doesn't; maybe (their) Hamachi is configured to forward the right ports for Doom3 but not for dhewm3 or something like that (I've never used Hamachi, does it have rules like that per game executable?)

**Comment by DanielGibson** [comment] 2021-02-15 17:50
Forgot to ask about:

> I actually was playing the whole campaign with a friend these days in order to test it, we fixed some stuff from alpha 1.1 and I hope to release a new version soon.

This sounds great, do you know when "soon" will be? More like two weeks or more like two months?
I will provide pre-compiled mod DLLs (or .so's for Linux) for the supported mods in the 1.5.1 release (like I did for 1.5.0) and I'd love to add a new version of LibreCoop to that collection :)

**Comment by Stradex** [comment] 2021-02-17 17:09
> This sounds great, do you know when "soon" will be? More like two weeks or more like two months?

I think that the new version is going to be released in one week at max. Unless I find a terrible bug. I'll keep you update if something happens that it is going to delay the release more than one or two weeks.

**Comment by DanielGibson** [comment] 2021-02-17 18:11
Sounds great, thank you!

**Comment by Stradex** [comment] 2021-02-20 22:49
If everything goes fine, between today or tomorrow I'll be able to publish the new version of Librecoop.

**Comment by DanielGibson** [comment] 2021-02-23 14:53
Awesome, thanks a lot @Stradex !

1.5.1 RC3 is out as well, please test, everyone (also with librecoop)!: https://github.com/dhewm/dhewm3/releases/tag/1.5.1_RC3
librecoop Alpha v1.2: https://www.moddb.com/mods/librecoop-dhewm3-coop/news/librecoop-alpha-12-released

**Comment by tyabus** [comment] 2021-02-23 16:20
I might host dhewm3 server with librecoop on linux soon.

**Comment by hemebond** [comment] 2021-03-07 08:30
It seems to load and play fine locally.

I see a "coop" game server in the multiplayer server list (the _only_ server I see in the list) but I can't seem to join it; unsure why because the error message is a missing string.

**Closed** 2021-04-12 13:34 UTC
