### ISSUE TITLE
Getting stuck on Initializing OpenGL subsystem

### ISSUE THREAD

**Issue by hazelnot** [dhewm/dhewm3#386] opened 2021-06-14 21:34 UTC
I'm trying to launch dhewm3 but it keeps getting stuck on `Initializing OpenGL subsystem`, no idea why.

I'm running it on Arch Linux. I pasted the terminal output into a text file:

[dhewm_log.txt](https://github.com/dhewm/dhewm3/files/6651420/dhewm_log.txt)

**Comment by DanielGibson** [comment] 2021-06-14 22:30
Weird - can you run it again with `+set developer 1` (in addition to your other arguments  to dhewm3) and post the output you get then?

Also, what GPU and driver are you using? Do other games work?

**Comment by hazelnot** [comment] 2021-06-15 08:24
I can't even copy the full output because it becomes an infinite string of ```Couldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find matching GLX visualCouldn't set GL mode 8/16/8: Couldn't find match```

Also I'm using a Radeon RX 5700 XT, with the default Mesa drivers, _from what I can tell_. Other games work just fine, yes.

**Comment by DanielGibson** [comment] 2021-06-15 15:03
Ahh, good to know - I think I just found a very stupid bug in that code that would explain your problem.

Can you test if this change fixes it: https://github.com/dhewm/dhewm3/commit/06390e893c4df52d79ddda1e195713d456c428a6 ?

(Or test the whole branch: https://github.com/dhewm/dhewm3/compare/gamma-in-shader)

Thanks in advance! :)

**Comment by hazelnot** [comment] 2021-06-17 11:33
The game launches on that branch, but now every texture is extremely messed up:

![Screenshot from 2021-06-17 14-32-25](https://user-images.githubusercontent.com/10992973/122388854-f5b16180-cf78-11eb-96db-02dc4f8b16bc.png)
![Screenshot from 2021-06-17 14-31-58](https://user-images.githubusercontent.com/10992973/122388860-f6e28e80-cf78-11eb-916d-2940a18745c0.png)

**Comment by DanielGibson** [comment] 2021-06-17 13:31
groovy!

can you post the new terminal output (with r_developer 1)?

**Comment by hazelnot** [comment] 2021-06-17 13:42
Is `r_developer 1` the same thing as `+set developer 1`?

**Comment by DanielGibson** [comment] 2021-06-17 13:43
yes, that's what I meant, sorry

**Comment by hazelnot** [comment] 2021-06-17 13:46
Here it is, menu + loading a save:

[dhewmlog2.txt](https://github.com/dhewm/dhewm3/files/6670667/dhewmlog2.txt)

**Comment by DanielGibson** [comment] 2021-06-17 14:13
Thanks!

This is weird - it looks absolutely ok: `Got 8 stencil bits, 24 depth bits, color bits: r8 g8 b8 a8` means that you got the 32bit color profile that was requested (I was thinking that maybe for some reason you only got 16 colors or something and that this might cause the flatshaded look), compiling/loading the shaders also succeeded (otherwise errors would've been logged) and there are no other errors or warnings either.

My best guess is that something is wrong with your driver - maybe a regression in support for OpenGL ARB shaders (almost noone uses them, which could explain that other games work)?
To narrow down the problem you could try if https://github.com/gabrielcuvillier/d3wasm works better - it can be compiled natively on Linux (not just for browsers) and uses a OpenGL ES 2.0 rendering backend with GLSL shaders

**Comment by hazelnot** [comment] 2021-06-17 14:26
Yup that works fine other than not being able to set my resolution to my actual native one

**Comment by DanielGibson** [comment] 2021-06-23 16:28
@Yamagi  ran into the same messed up texture problem (but not the getting stuck problem) and it turned out that it was introduced with this commit: https://github.com/dhewm/dhewm3/commit/dc42bdc873f2c64497a1c5418fdda4d3d739af64
And more specifically, is triggered by `reloadARBprograms`, even when manually running that console command in older versions of dhewm3.

Furthermore, I still can't reproduce that issue on my XUbuntu 20.04 box with an Radeon RX580; he's using an RX 5700XT on Arch Linux.
My relevant version lines from `glxinfo`:
`OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-74-generic, LLVM 11.0.0)`
`OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.6`
His corresponding lines:
`OpenGL renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.40.0, 5.12.8-1-custom, LLVM 11.1.0)`
`OpenGL version: 4.6 (Compatibility Profile) Mesa 21.1.1`

So it seems possible that either this is a Polaris vs Navi problem or, more likely, an issue introduced in Mesa 21 (or at least in some version between 20.2.6 and 21.1.1).

As it works everywhere else (and on older mesa versions; also on the same XUbuntu 20.04 version with an intel iGPU on my laptop) this looks like a regression in Mesa, though I have no idea why it would be broken only after reloading the shaders.
I might be able to work around it by making sure the shaders are only loaded once at startup.

**Comment by hazelnot** [comment] 2021-06-23 17:13
Here's my ```glxinfo``` stuff, in case it helps:

```OpenGL renderer string: AMD Radeon RX 5700 XT 50th Anniversary (NAVI10, DRM 3.40.0, 5.12.12-arch1-1, LLVM 12.0.0)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.1.3```

**Comment by DanielGibson** [comment] 2021-06-23 17:38
Thanks!

**Comment by DanielGibson** [comment] 2021-06-24 16:39
I just pushed a fix to the master branch that should fix this issue, can you test it?
Thanks! :)

**Closed** 2021-06-24 16:38 UTC

**Comment by hazelnot** [comment] 2021-06-25 15:50
Hey it worked! Thanks!

**Comment by DanielGibson** [comment] 2021-06-26 18:58
I installed the oibaf PPA mesa version (21.2.0-devel 2021-06-26) on my machine with the Radeon RX580 and can reproduce the glitches, so it seems like the bug indeed is specific to newer Mesa versions (and not to Polaris vs Navi)

**Comment by DanielGibson** [comment] 2021-06-27 23:35
I created a bugreport at Mesa's bugtracker: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5001
