### ISSUE TITLE
lighting problem on Raspberry Pi 2 stretch

### ISSUE THREAD

**Issue by pinilpypinilpy** [dhewm/dhewm3#186] opened 2018-03-03 19:23 UTC
I compiled dhewm3 on the raspberry pi 2, and the game loads with all the lowest settings (note: when loading the game, it does not say "loading" but "#str"and some numbers).  I get around 20fps. However, almost everything is black and it is impossible to see anything except for light sources (which glow but don't light up the area around them). I don't think it's a problem with the low settings, as I copied some of the settings from http://henrike.se/d3/DoomConfig.cfg which was modified to run on a pi2 ( but with a different renderer that used gles2.0) and worked fine for other people: https://www.raspberrypi.org/forums/viewtopic.php?t=99624. I also used the dhewm3 config file with all the setting turned to low but got the same result.
thanks, pinilpypinilpy.

**Comment by pinilpypinilpy** [comment] 2018-03-07 13:45
I just ordered an Asus tinkerboard, and when it arrives I'll compile dhewm 3 with glshim and see how it works.

**Comment by DanielGibson** [comment] 2018-03-07 14:22
Note that whatever problems you run into are most probably due to buggy drivers and I don't think I can do much about them.
Part of the problem is probably Doom3's old OpenGL renderer using those stone age ARB assembly shaders instead of GLSL - but at least I have no motivation (or time) to rewrite the renderer (and all the shaders!) in more modern OpenGL.
But if someone ported the Dante GLES2.0 compatible renderer to dhewm3 (while still allowing to at least at compiletime, ideally at runtime, select the original renderer) I'd happily accept a pull request :)

**Comment by johndoe71rus** [comment] 2018-07-15 05:16
i have similar problem, but not raspberry. Black walls and floor. Can see only some objects. 
start log https://paste.ubuntu.com/p/DjXmgVqhYF/
but many WARNING: Couldn't load image:
https://paste.ubuntu.com/p/K79fPcqgc5/
https://i.imgur.com/BzZnbZe.png
https://i.imgur.com/BGzY8WH.png

this problem with game resources or video driver/card ?
glxinfo https://paste.ubuntu.com/p/4cZSP7stsr/

**Comment by DanielGibson** [comment] 2018-07-19 13:55
This is weird.
Do you have any game data that's not directly from doom3 1.3.1 installed? like fan missions or retexturing packs? (Try removing that)
Have you tried another texture quality (both ultra and something lower than the current are worth a try)?

At first I thought maybe your driver doesn't support S3TC texture compression and it can't load Doom3's .dds textures because of that, but according to glxinfo s3tc *is* supported so that shouldn't be the problem either.

**Comment by Yamagi** [comment] 2018-07-19 15:46
I just tested this on my Radeon R3 360 and dhewm3 works like a charm, no render errors or else. That's not really comparable, though. The HD4670 is a TerraScale (aka r600) card, while my R3 360 is a GCN card. They have totally different programming models and driver stacks. On the other hand was the last TerraScale series the HD6000 which is now nearly 7 years old. Is it really worth the effort to invest time in debugging such an old GPU architecture with very limited upstream support?

**Comment by DanielGibson** [comment] 2018-07-19 16:11
Thanks for testing!

I think we can be reasonably sure that it's some kind of driver problem (either the driver is buggy or maybe not probably configured/installed).
So, like in the RPi case, I don't think there's anything I can do about it.
You could try filing a bug at https://bugs.freedesktop.org/

**Comment by johndoe71rus** [comment] 2018-07-19 18:17
@Yamagi 
doom3 was released in 2004. Last patch 1.3.1 was in 2007. so hd4670 and doom 3 came from one time

**Comment by DanielGibson** [comment] 2018-07-19 18:34
Yes, and I'm sure if you use an (official closed source) ATI/AMD driver from that era the game will work.
Of course that driver will not work on modern operating systems..

But because the GPU is that old, it's not super-likely that people will investigate bugs in its open-source driver (because the developers mostly work on drivers for newer cards). I might be wrong though, and filing a but can never hurt.

**Comment by johndoe71rus** [comment] 2018-07-19 18:58
can you advise how to check the game for the presence of mods?
I found that there are native versions of games. I try to build them from the source code and run.

**Comment by DanielGibson** [comment] 2018-07-19 19:02
are any .pk4 files except for `pak000.pk4` to `pak008.pk4` in `base/`?

**Comment by DanielGibson** [comment] 2018-07-20 00:17
oh yeah, related idea: maybe your .pk4s are damaged and that's the reason the textures can't be loaded.
Please check md5sums and compare with those from https://dhewm3.org/#getting-the-doom3-game-data

**Comment by DanielGibson** [comment] 2018-07-24 13:05
Yeah, your MD5 sums are incorrect, probably the game data is broken or incompatible.
I *think* that all language versions of the game should have the same paks with the same MD5 sums, and additional language-specific `.zpak` files. Those are not supported by the Doom3 GPL release (and thus not by dhewm3); they also weren't supported by the original Doom3 Linux binaries released by id Software back in the day.

So I'm not sure what kind of game data you have there, maybe an inofficial or patched release or something?
Whatever it is, we only support the original `.pk4` files with the MD5 sums listed at https://dhewm3.org/#getting-the-doom3-game-data
Please try obtaining those and test them, and tell us if this doesn't fix your problem after all.

**Closed** 2018-11-10 17:17 UTC
