### ISSUE TITLE
Release of dhewm3

### ISSUE THREAD

**Issue by coldtobi** [dhewm/dhewm3#106] opened 2015-02-25 20:22 UTC
Hi Daniel,

Just a wishlist bug: Can you please consider making a release tarball? Would be great for my Debian packaging efforts to have a release version.. Currently I use version "0~git<datestamp>.
For the version, maybe we could continue from the original versioning, so something along 1.3.2 ?

Thanks for considering :)

And of course kudos for the effort of the project!

coldtobi

**Comment by DanielGibson** [comment] 2015-02-25 20:25
I guess a release git tag should be enough (I think github will provide a tarball for that then)?

I'm not sure about the right version number, it should probably be at least 1.4 or even 2.0 if it's supposed to continue the old versions, because it's not binary-compatible with old mod .dll/.so

**Comment by coldtobi** [comment] 2015-02-25 20:55
Am Mittwoch, den 25.02.2015, 12:25 -0800 schrieb Daniel Gibson:
> I guess a release git tag should be enough (I think github will
> provide a tarball for that then)?

Never tried myself, but I guess it is that way. I found this:
https://help.github.com/articles/creating-releases/

> I'm not sure about the right version number, it should probably be at
> least 1.4 or even 2.0 if it's supposed to continue the old versions,
> because it's not binary-compatible with old mod .dll/.so

Sounds sane... I think it's your pick :)

Mmm, I just remember that I have a small typo-fixing patch.
Might be cool to get that in too. I'll report another issue & give you a
merge request ;-)

**Comment by DanielGibson** [comment] 2015-02-25 21:14
Ok, I think I'll create a release (most probably 1.4.0) in the next days, I wanna check if there's anything I'd like to do before that first.

Thanks for packaging this for debian! :-)

BTW, did you check whether https://github.com/dhewm/dhewm3/issues/104 affects your package?  The bugreport mentions jessie, but sid seems to use the same version of libvorbisfile3.  
https://github.com/dhewm/dhewm3/issues/104#issuecomment-70389920 describes how to reproduce the problem and how I failed to reproduce it on Mint even when building from the same source.

**Comment by burito** [comment] 2015-03-24 12:17
I got impatient and created some binaries for Mac, Windows and Ubuntu 14.04 [here](http://danpburke.blogspot.com.au/2015/03/dhewm3-1311304-x8664-binaries-2015-03-23.html). I think I ticked all of the boxes regarding licenses. Does dhewm3 have a place for distributing binaries?

**Comment by DanielGibson** [comment] 2015-03-24 16:09
The reason I'm delaying the release is bug #104.

When I release I wanna add binaries to the release to download, especially your OSX binary is very welcome :-)

(Github only allows adding "Downloads" as part of releases)

**Comment by burito** [comment] 2015-03-24 18:15
> Built with backwards compatibility up to 10.5 or something (whatever is feasible)

10.5 has been unsupported by Apple since 2011, Google Chrome and Firefox since 2012.

Regarding 10.6 and onwards, well, [this page](http://www.apple.com/osx/how-to-upgrade/) should alleviate your concerns.

**Comment by DanielGibson** [comment] 2015-03-24 18:16
no it won't, if someone has older apple hardware he can't upgrade.

a friend of mine has an old macbook that only supports up to 10.6, for example.

**Comment by burito** [comment] 2015-03-24 18:50
An 8 year old 32-bit Intel Mac? That means it would have the Intel GM940 integrated GPU, which supports OpenGL 1.4. You think this can run Doom3?

**Comment by DanielGibson** [comment] 2015-03-24 18:55
an 8 year old laptop could possibly run a 10 year old game, at least on low details.

**Comment by burito** [comment] 2015-03-24 19:08
[This](https://www.youtube.com/watch?v=nz8tcATvJ7A) is 2 models up from that GPU, the GM950 (there was a GM945 in the middle).

**Comment by DanielGibson** [comment] 2015-03-24 19:10
according to http://arstechnica.com/apple/2013/06/psa-os-x-10-9-appears-to-run-on-any-mac-that-can-run-os-x-10-8/ there's even hardware that was sold in 2008 that doesn't support 10.9 or newer.  
I'm not very familiar with Apple's product portfolio, but I can imagine that this also affects products that could run doom3 better than intel GM940.

**Comment by burito** [comment] 2015-03-24 19:18
10.8 was the one that dropped non-EFI hardware, anything running 10.8 will run all the newer versions. Still, that is definitely capable of running Doom3 at a reasonable level.

So...
10.5 : PowerPC
10.6 : 32bit
10.7 : non-EFI
>=10.8 : upgrade to 10.10

Handy to know. (I wish Apple would outline this stuff)

**Comment by DanielGibson** [comment] 2015-03-24 19:24
AFAIK, targeting a minimum OSX version isn't that hard anyway, some flag somewhere in xcode or something. So it shouldn't be "harder" to build binaries for 10.5 or 10.8.

SDL2's official binaries support down to 10.5.

**Comment by coldtobi** [comment] 2015-09-22 16:59
The underlaying problem of #104 is now fixed in Debian... Should we get ready for the release?

**Comment by DanielGibson** [comment] 2015-09-22 17:17
Yeah, I guess so ;-)

I hope I get around to it this weekend.

I thought about updating the https://github.com/dhewm/dhewm3-libs repo as well, as the libs there are all outdated, but doing that doesn't seem fun :-/
SDL2 and openal-soft provide binaries (incl. development stuff) for windows, maybe I can just drop that there.. I guess updating ogg/vorbis, zlib and libjpeg isn't that important. cURL might be, though.
But in the end I could always do that after tagging a release.

**Comment by DanielGibson** [comment] 2015-09-28 01:00
The release won't happen just yet, but I already did lots of small improvements and bugfixes that can be tested.
The mingw build is being a pain in the ass and I didn't test MSVC yet..

Most things are in master, one more invasive (and butt-ugly) change is in https://github.com/dhewm/dhewm3/tree/widescreen
It's a rather ugly hack to add more resolutions (primarily widescreen resolutions) to the video settings menu and I'm not sure yet if I wanna merge it into master before the release, as it hasn't be tested much (works for me, but ...)

**Comment by DanielGibson** [comment] 2015-10-03 02:49
Ok, the current plan is like this: tomorrow (Saturday) I'll release 1.4.0 Release Candidate 1 incl. Windows binaries, hoping that more people will test it (several people already tested it this week, but mainly on Linux).

If I get enough feedback (and no big bugs occur/I can fix them quickly): Sometime next week (-end?) I'll finally release 1.4.0

(The widescreen stuff is in master now, btw)

**Comment by DanielGibson** [comment] 2015-10-05 14:59
So far the feedback has been very positive, except for https://github.com/dhewm/dhewm3/issues/122 which happened exactly once to one person and couldn't be reproduced since.
So unless someone can deterministically reproduce this, it won't be fixed for release.

Unless something huge turns up in the next days, my plan is to release around Friday.

@burito can you test the current code on OS X? Thanks in advance :-)

**Comment by coldtobi** [comment] 2015-10-05 19:15
Hi Daniel,

built and tested a bit the current snapshot for Debian -- looks good so far!

**Comment by DanielGibson** [comment] 2015-10-09 15:30
Done, see https://github.com/dhewm/dhewm3/releases/tag/1.4.0

**Closed** 2015-10-09 15:31 UTC

**Comment by burito** [comment] 2015-10-30 04:43
MacOSX build works 100%.

Interesting selection of video modes it has. Missing 2880x1800, the native
res of the "MBP retina 15-inch mid 2014". Still it runs quite nicely on
2560x1600, the nearest resolution.

Sorry for the delay, on holiday in Berlin ATM.

regards,

dan
--
"The world is full of magical things patiently waiting for our wits to grow
sharper." - Bertrand Russell

**Comment by DanielGibson** [comment] 2015-10-30 18:32
Thanks for testing!

I can add the mode - it'll be r_mode 22, I'll have to see if it's easy to sort it "correctly" (between 2560x1600 and 3200x2400) in the menu

**Comment by DanielGibson** [comment] 2015-10-30 18:38
Oh by the way, if you happen to visit Hamburg too, we could get a beer or something :-)

**Comment by DanielGibson** [comment] 2015-10-30 20:43
ok, added support for your resolution and sorting of the vidmodes in the menu.
