### ISSUE TITLE
No text on BigEndian

### ISSUE THREAD

**Issue by tlosm** [dhewm/dhewm3#148] opened 2016-07-18 18:19 UTC
Hi devs on bigendian text are not displayed 
if you need some logs or more please ask 
attached an image
![screenshot from 2016-07-18 20-18-51](https://cloud.githubusercontent.com/assets/18098090/16925513/e89967ee-4d24-11e6-9d49-39bb03590347.png)

**Comment by DanielGibson** [comment] 2016-07-19 20:25
uhh.. no idea, sorry. I can't reproduce the problem because I don't have any big endian hardware, and thus I can't debug it :-(

In case anyone else can debug this, what operating system and hardware are you using?

**Comment by tlosm** [comment] 2016-07-19 20:43
Hi Daniel, Im using Ubuntu Mate 16.10 on AmigaOne X5000 Freescale P5020 (dual 2ghz)with RadeonHD 6570 2GB , but i have the Same issue on a Quad G5 with Ubuntu Mate 15.10 with Radeon HD 4650 512mb . A friend of mine same issue on P6T 6870 1GB (all this machine are big endian) 
If you have a good horse powered machine you can use qemu-system-ppc with ubuntu mate emulated not fast but working .

**Comment by DanielGibson** [comment] 2016-07-19 22:10
Does qemu support OpenGL now? (Haven't used it in years.. not since Open Source VirtualBox came out for Linux, I think)

**Comment by tlosm** [comment] 2016-07-20 06:57
Yes thru virgl3d and with passthru. but for now not in the emulated hw only in virtualized. they made big steps in last year.

**Comment by DanielGibson** [comment] 2016-07-20 22:50
so that doesn't help me much..

I guess you're using a 64bit OS and 64bit dhewm3 binaries?
If so, can you build and run 32bit binaries (like x86 binaries on amd64)? Do they have the same bug?
If this is not possible, do you or one of your friends have a PPC G4 system or something like that with a 32bit OS where you can test?

(Generally, Doom3 should support PPC/big endian, at least it originally worked on OSX/PPC, so I wonder if it's a 64bit PPC problem. Of course it is entirely possible that we introduced the bug in the changes we did to the original source, but testing this might narrow the problem down.)

**Comment by DanielGibson** [comment] 2016-07-23 21:45
Furthermore, I wonder if all text is missing. Can you open the console (Shift+Esc)? Any text there?

**Comment by tlosm** [comment] 2016-07-24 08:01
Hi Daniel, 
negative the text in the console are show right, only the in game (datapad, terminal etc) and menu are missing

**Comment by DanielGibson** [comment] 2019-01-13 07:04
(someone else who actually has Big Endian hardware will have to debug this)

**Comment by dhewg** [comment] 2019-02-14 16:05
Since the issue isn't exactly new... I've also seen radeon endian fixes for kernel and mesa over the years. Maybe it's fixed by now? Does the problem still occur?

**Comment by SiliconExarch** [comment] 2020-12-25 15:29
I can confirm the problem does still occur. I'm using Void Linux (Kernel 5.10.1) on a Power Mac G5 (Late 2005) with a Radeon HD6670.

**Comment by DanielGibson** [comment] 2020-12-26 03:26
Thanks for testing!
Still seems likely that it's a driver bug (possibly related to OpenGL ARB shaders, they're not widely used AFAIK so big-endian bugs in them can probably go undetected for years? just a wild guess though).

**Comment by SiliconExarch** [comment] 2020-12-26 20:32
I plan on testing a 32-bit PPC build for completeness but I'm out of hard drive space on the Mac so I'm waiting for some additional storage I've ordered to arrive.

**Comment by Cowcat5150** [comment] 2020-12-29 08:48
In my system (Morphos) the way to fix it is adding "|| define(__PPC__)" to the other __ppc__ in tr_fonts.cpp / readFloat function.

**Comment by DanielGibson** [comment] 2020-12-29 14:39
To get code to show correctly, put backticks around it, like
```
`#ifdef __PPC__`
```
which will turn into `#ifdef __PPC__`
For multiple lines, you can use three backticks before and after the code block, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

@SiliconExarch can you try if, in neo/renderer/tr_font.cpp in the `readFloat()` file, replacing `#ifdef __ppc__` with `#if defined(__ppc__) || defined(__PPC__` fixes the issue on your system as well?
(Probably the clean fix would be to check for big endian instead of PPC, I'll look into that)

**Comment by DanielGibson** [comment] 2020-12-29 14:53
Better solution: replace the `readFloat` implementation with this:
```c++
float readFloat( void ) {
	float f;
	memcpy(&f, &fdFile[fdOffset], 4);
	fdOffset += 4;
	return LittleFloat(f);
}
```
(if this works for you, I'll commit it)

**Comment by Cowcat5150** [comment] 2020-12-29 21:24
Could be helpfull if someone else finally compiles a 32-bit ppc on other systems and check problems.

Got a cut down version that half works but that's for another thread.

**Comment by Nable80** [comment] 2020-12-29 22:36
> ``memcpy(&f, &fdFile[fdOffset], 4);``
> ``fdOffset += 4;``

> _4_

``sizeof(f)`` is much better here, isn't it?

**Comment by DanielGibson** [comment] 2020-12-30 00:31
if sizeof(float) != 4 this code will break completely anyway (that data we're operating on there comes from a file).
Luckily I'm not aware of any architecture where `float` isn't a IEEE 754 32bit (4byte) "single precision" float (at least none that would be able to run Doom3 at all).

**Comment by Nable80** [comment] 2020-12-30 22:46
I thought C++ standard says something about IEEE-754 and floating point types (I've tried to find a reference now, unfortunately it looks like the standard isn't strict enough here). Anyway, my idea was about getting rid of "magic" constants where symbolic replacement is straightforward and easy to understand (i.e. less likely to cause WTF moments). ``WriteFloat`` uses sizeof, so my idea didn't look inconsistent with the whole codestyle. Just my $0.02.

**Comment by DanielGibson** [comment] 2021-01-08 13:15
Has anyone tried my suggested fix yet?

**Comment by Cowcat5150** [comment] 2021-01-09 10:21
Works for me.

**Comment by DanielGibson** [comment] 2021-01-14 11:26
thanks for testing, I committed the fix

**Closed** 2021-01-14 11:25 UTC
