### ISSUE TITLE
wayland: regression with imgui-rebased   ( https://github.com/dhewm/dhewm3/pull/576 )

### ISSUE THREAD

**Issue by j4reporting** [dhewm/dhewm3#587] opened 2024-07-02 14:49 UTC
found  easy  procedure  to crash dhewm3  on linux with wayland ( didn´t test with x11) 

wayland/gnome 
desktop resolution 2560x1440@144z  (nvidia driver 555.58.02 )

SDL_VIDEODRIVER=x11   // no problem  with SDL_VIDEODRIVER=wayland
with X11  the resolution used by SDL changes to desktop resolution 

```
r_fullscreenDesktop = "0"
r_fullscreen = "0"

r_mode = "-1" 
r_customHeight = "1080"
r_customWidth = "1920"
```
works with dhewm 1.5.3   

several ways to reproduce

1) in main screen
alt/enter  to fullscreen 
alt/enter  to window  -> crash

2) in main screen
alt/enter  to fullscreen
open imgui 
select video tab -> crash

3) in main screen
open imgui/video
change from Windowed to Fullscreen 
apply ->  crash 

bt is not very useful,  need to get libbacktrace  and recompile

```
----- Initializing Session -----
in_grabKeyboard: Will *not* grab the keyboard if mouse is grabbed, so global keyboard-shortcuts (like Alt-Tab) will still work
----- Game Map Shutdown -----
'vid_restart partial' succeeded in changing resolution and/or fullscreen mode
dhewm3: /home/markus/src/github/doom3/dhewm3-imgui/neo/sys/glimp.cpp:749: glimpParms_t GLimp_GetCurState(): Assertion `ret.width == glConfig.winWidth && ret.height == glConfig.winHeight' failed.


Looks like dhewm3 1.5.4pre crashed with signal SIGABRT (6) - sorry!

```

dhewm 1.5.3    switches seamlessly  to full screen  2560x1440    and back to the configured resolution in windowed mode. 

```

]r_fullscreen 1
]vid_restart 
Shutting down sound hardware
Shutting down OpenGL subsystem
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Will create a fullscreen-window with resolution 1920x1080 (r_mode = -1)
SDL detected 1 displays: 
 0: 2560x1440 at (0, 0) to (2560, 1440)
Will use display 0 because mouse cursor is at (1946, 639).
Requested 8 color bits per chan, 8 alpha 24 depth, 8 stencil
Got 8 stencil bits, 24 depth bits, color bits: r8 g8 b8 a8
OpenGL vendor: NVIDIA Corporation
OpenGL renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL version: 4.6.0 NVIDIA 555.58.02


r_fullscreen 0
]vid_restart 
Shutting down sound hardware
Shutting down OpenGL subsystem
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Will create a window with resolution 1920x1080 (r_mode = -1)
SDL detected 1 displays: 
 0: 2560x1440 at (0, 0) to (2560, 1440)
Will use display 0 because mouse cursor is at (1462, 1048).
Requested 8 color bits per chan, 8 alpha 24 depth, 8 stencil
Got 8 stencil bits, 24 depth bits, color bits: r8 g8 b8 a8

```

**Comment by DanielGibson** [comment] 2024-07-02 15:56
Does that also happen in the current master branch? Because imgui-rebased as been merged

**Comment by DanielGibson** [comment] 2024-07-02 16:05
Ok - can you tell me what imgui menu -> video options says about "Current Resolution" and "Display Size", both in windowed mode and fullscreen mode (if needed because using imgui menu crashes on apply, configure that through console and use a full `vid_restart`)

**Comment by DanielGibson** [comment] 2024-07-02 16:36
does it say anything about "Physical" (it does when detecting display scaling) in the menu, next to Current Resolution and Display Size?

**Comment by Yamagi** [comment] 2024-07-02 17:22
If I understand the problem right this behavior is kind of expected: Under Wayland the fullscreen handling is compositor dependent. In my experience tho common compositors (kwin, mutter, wlroots) don't support implement switching initiated by clients. When a client requests fullscreen mode, the client is a) put in exclusive fullscreen mode when it's drawable size matches the current resolution of the given display or b) scaled up / down if it's drawable size is lower / higher than the resolution of the given display. Fractional scaling and scaling awareness of the client *shouldn't* matter in exclusive fullscreen, the common compositors communicate a scaled display mode, but an unscaled drawable size. That might break assumptions made by the client, though.

**Comment by DanielGibson** [comment] 2024-07-02 17:26
Does it help if at the end of GLimp_SetScreenParms(), around here: https://github.com/dhewm/dhewm3/blob/master/neo/sys/glimp.cpp#L685, maybe after that `glConfig.isFullscreen = (SDL_GetWindowFlags( window ) & SDL_WINDOW_FULLSCREEN) != 0;` line, you add
`GLimp_UpdateWindowSize();` ?

**Comment by DanielGibson** [comment] 2024-07-02 18:06
> no change.

ok, I'll have to debug this on wayland

> all what was needed was commenting out the assert at line 728

that's no solution - if the values in glConfig aren't correct (consistent with the actual sizes), other code will behave wrong (for example mouse cursor speed, possibly even rendering itself)

**Comment by DanielGibson** [comment] 2024-07-02 23:15
I pushed a fix for this to master.

Overall that case is still kinda broken (no crash anymore, but mousecursor behaves weird), and that's a bug in SDL or Wayland.

I think the main underlying issue is that **Wayland does *not* support real fullscreen mode**.
It does not allow applications to switch the resolution (or display refreshrate, by the way).

So all you get is fugly hacks: In the **native Wayland case** (`SDL_VIDEODRIVER=wayland`) the Window uses the given resolution (1920x1080 in your case) but the compositor scales it to be a borderless fullscreen window (at 2560x1440 in your case). So the window renders at the lower resolution and all the coordinates are at that resolution and it at least kinda works.

In the **XWayland** case however it apparently creates a borderless fullscreen window at the desktop resolution (2560x1440 in your case, *not* the one you requested!). For some reason however, one SDL function (`SDL_GetWindowDisplayMode()` - which is supposed to return the resolution for the currently used fullscreen mode!) returns the requested resolution (1920x1080), while another (`SDL_GetWindowSize()` returns the actual resolution (2560x1440).

Due to dhewm3 using the wrong size (at least consistently now..), the mouse input can behave weird in this specific case (XWayland + "real" fullscreen at lower resolution).

Extra unfortunate: think in the past I've seen `SDL_GetWindowSize()` *not* returning the correct resolution when in real fullscreen mode (on systems that, unlike Wayland, actually support that), so I don't really want to use SDL_GetWindowSize() for everything..

**Comment by DanielGibson** [comment] 2024-07-03 00:42
> So the mouse cursor could behave strangely in the GUI /PDA ? But mouse movement in game should not be affected?

Yeah, I think so. I specifically noticed that the cursor position in ImGui isn't consistent with the one in the main menu anymore.

I recommend using only "fullscreen desktop" mode with Wayland, because real fullscreen isn't supported anyway.
Though if you want to run the game at a lower resolution for performance reasons (but scaled over the whole screen), "real" fullscreen with native Wayland probably works well enough.

**Comment by DanielGibson** [comment] 2024-07-03 02:15
> Wouldn't SDL_GL_GetDrawableSize() be a more suitable call? It should report the real dimensions of the drawable.

No, because the mouse coordinates don't use the drawable size but the window size (when they're different, like in HighDPI/desktop scaling mode).

> is something like this available in doom3?

You can also use aliases and all that, but the easiest way is to enable fullscreen desktop (r_fullscreenDesktop) mode.
Then the configured resolution will only be used (and remembered) for windowed mode, and when pressing Alt-Enter (or generally enabling r_fullscreen) dhewm3 will switch to a borderless fullscreen window at the current display resolution. It looks just like normal fullscreen.

**Comment by DanielGibson** [comment] 2024-07-03 15:08
uhh.. wtf.. didn't have that issue

is this on master or kickstart-my-hertz?

**Comment by DanielGibson** [comment] 2024-07-03 17:16
Does it only look broken in screenshots or also on the actual screen?

So far I really can't reproduce this, even with Wayland + Gnome

**Comment by DanielGibson** [comment] 2024-07-03 18:12
I tested with latest Arch Linux (live image with Gnome from http://dl.gnutux.fr/archuseriso/img/, but updated that while running and additionally installed gnome-control-center) on a laptop with AMD iGPU (Ryzen 5 7640U).

I just had a maybe similar issue: When changing the resolution (or toggling fullscreen) *after taking a screenshot*, the window remained black or invisible.
I just pushed a potential fix for that to the kickstart-my-hertz branch, can you test if it also resolves your bug? :)

**Comment by DanielGibson** [comment] 2024-07-03 20:08
I don't really see much in the video, maybe due to the low resolution.
Does it still happen both with SDL_VIDEODRIVER=wayland and the default (XWayland)?

I tested with the space ship at the beginning of the game and didn't see any graphical bugs there. I'll test again with the Infirmary

Could also be a graphics driver bug, of course

**Comment by DanielGibson** [comment] 2024-07-03 20:52
Ok, with the downloaded video I can see that it looks wrong.

Can't reproduce it though.

Here it's the same XWayland and mutter versions, but SDL 2.30.**4** (and of course no nvidia driver but the open source AMD driver)

**Comment by DanielGibson** [comment] 2024-07-03 21:15
Can't reproduce it with real X11 and nvidia driver 535.183 either.

However, I just added a CVar `r_vidRestartAlwaysFull` that forces all vid_restarts to be full.
You should also set `r_windowResizable 0`, because when resizing a window by dragging or maximizing it, vid_restart isn't called at all.

**Comment by DanielGibson** [comment] 2024-07-04 15:43
So do you think we can consider this bug resolved (from dhewm3's point of view, I can't do anything about nvidias driver) by setting `r_vidRestartAlwaysFull 1`?

**Comment by DanielGibson** [comment] 2024-07-04 16:10
Great!

**Closed by DanielGibson** 2024-07-04 16:10 UTC
