### ISSUE TITLE
leadin sound not played for looping sound shaders

### ISSUE THREAD

**Issue by IvanTheB** [dhewm/dhewm3#291] opened 2020-05-19 20:41 UTC
Given the following shader, the leadin sound is played in vanilla D3, but not in dhewm.

Steps to reproduce:

1. Save the following in sound/bug.sndshd 
``` 
loop_with_leadin {
	minDistance	2
	maxDistance	25
	volume		7
	looping

	leadin sound/weapons/chaingun/cg_windup_mix_01.wav
	sound/weapons/chaingun/cg_motor_loop_01.wav
}
```
2. run game and type:  `testSound loop_with_leadin`

**Comment by DanielGibson** [comment] 2020-05-23 21:01
(I've transferred this issue to the dhewm3 repository because it's a bug in the engine, not in the SDK-part of the code)

I'm pretty sure this issue already existed in original Doom3, at least when using OpenAL (dhewm3 only supports OpenAL for sound output).
It's here:
https://github.com/id-Software/DOOM-3/blob/master/neo/sound/snd_world.cpp#L1755

The problem is:
```c++
	if ( ( !looping && chan->leadinSample->hardwareBuffer ) || ( looping && chan->soundShader->entries[0]->hardwareBuffer ) ) {
		// handle uncompressed (non streaming) single shot and looping sounds
		if ( chan->triggered ) {
			alSourcei( chan->openalSource, AL_BUFFER, looping ? chan->soundShader->entries[0]->openalBuffer : chan->leadinSample->openalBuffer );
		}
	} else {
		// ...
```
`looping && chan->soundShader->entries[0]->hardwareBuffer` is true for looping sounds where the main sound is a .wav (not .ogg) (hardwareBuffer means it just uploads all the raw sound data from the .wav into the OpenAL buffer that is played).
`alSourcei( chan->openalSource, AL_BUFFER, looping ? chan->soundShader->entries[0]->openalBuffer : chan->leadinSample->openalBuffer )` means that if `looping` is true, alSourcei() tells the source to use the `chan->soundShader->entries[0]->openalBuffer` buffer - that's the one of the main (looping) sound, not the leadin.
Also, a few lines above: `alSourcei( chan->openalSource, AL_LOOPING, ( looping && chan->soundShader->entries[0]->hardwareBuffer ) ? AL_TRUE : AL_FALSE );` sets the source to AL_LOOPING if `looping` is true and the main sound is a .wav.
This means that just the main sound is used and looped by openal.
(the else-case of the code above is much more complicated and handles streaming from .ogg, but it also handles leadin sounds and switching from leadin to "main" sound correctly)

Anyway, I think I have a fix in the following branch: https://github.com/dhewm/dhewm3/tree/fix-looping-sound-leadin
Can someone test it? I only tested a bit with `testSound` in the console (and only on Linux), I think this should be tested a bit more thoroughly before it goes into master.

**Comment by IvanTheB** [comment] 2020-05-27 16:29
@DanielGibson Thanks a lot for this! I'll test it in the next days!

**Comment by DanielGibson** [comment] 2020-05-29 01:19
I created a fresh (Win32) build with this fix (and some more) included, based on the [openal-fixes branch](https://github.com/dhewm/dhewm3/tree/openal-fixes)): [dhewm3-oal-fixes.zip](https://github.com/dhewm/dhewm3/files/4699110/dhewm3-oal-fixes.zip)
Please test! :)

**Comment by IvanTheB** [comment] 2020-05-30 10:26
Your fix seems to have solved the issue. Thanks!
I'll now play the game some more paying particular attention to sounds. 
I'll report my findings here within a couple of days.

**Comment by IvanTheB** [comment] 2020-06-01 16:22
I played some more maps and I didn't find any issue with your fixes. :D
I think we can close this once they are merged!

**Comment by DanielGibson** [comment] 2020-06-01 16:25
Awesome, thanks for testing!

**Closed** 2020-06-01 20:14 UTC

**Comment by DanielGibson** [comment] 2020-06-01 21:35
This fix in master, but I have another OpenAL related fix that needs testing, see https://github.com/dhewm/dhewm3/pull/296

There you can also get Windows binaries for  testing that include all the OpenAL fixes of the build linked above, the aforementioned timing fix and latest changes from master.
Thanks in advance for testing! :)
