### ISSUE TITLE
CG cutscenes got stretched in widescreen

### ISSUE THREAD

**Issue by Evilbaka** [dhewm/dhewm3#189] opened 2018-03-29 21:28 UTC
As written above, in 16:9 mode I expected black bars at logos and cutscenes but insted they got stretched to full screen which is ugly.

**Comment by DanielGibson** [comment] 2018-10-28 04:31
This is a duplicate of #188, and I also just pushed a commit that fixes this - please test! :)

**Closed by DanielGibson** 2018-10-28 04:31 UTC
