### ISSUE TITLE
Weapon sound volume issue

### ISSUE THREAD

**Issue by jyudoki** [dhewm/dhewm3#326] opened 2020-11-11 14:54 UTC
In this video https://www.youtube.com/watch?v=te0mZ5Asa00 you'll notice that weapons 5-9 sound equal in volume to 1-4. In the game however, weapons 5-6 sound much weaker compared to other weapons and other sounds. I've seen a number of videos of vanilla Doom 3 (presumably running on older hardware?) that sound just like in this video.

I can confirm this is an issue with both the vanilla version of Doom 3 on my PC as well as this source port, so not sure if this is due to modern hardware or a bug?

**Comment by DanielGibson** [comment] 2020-11-15 06:12
Which weapons do you mean, chaingun and grenades?

Could be due to OpenAL vs old sound backends (Doom3.exe supports both, dhewm3 only supports OpenAL).
Or maybe id Software reduced the weapon sound volumes in an update?

**Comment by jyudoki** [comment] 2020-11-15 06:18
The chain gun, rocket launcher and BFG are the most obvious. I have also played around a bit with the equaliser for my headphones and i can make it less obvious.

The bigger issue is the ladder bug that I posted thats been in the game since day 1. Any chance of being able to fix that?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkcharmander** [comment] 2020-11-15 23:37
With EAX enabled, it seems to me that the Shotgun sounds really weak, just like the Chaingun. When I disable EAX, the Shotgun sounds louder, but the Chaingun sounds relatively weak still. It could just be my imagination, but I think that the sound of all weapons should have a bit more volume and 'Oomph'!

**Comment by DanielGibson** [comment] 2020-11-15 23:57
dhewm3 doesn't change any weapon sound settings or similar, but it's possible that its EAX/EFX support sounds a bit different than in the original (where EAX only worked with Creative Labs soundcards, IIRC?).

The changes with EAX disabled are probably due to OpenAL - either you're comparing the sound with the old sound backend, or modern OpenAL sounds a bit different to the openal32.dll you used back then.
You said that even Vanilla Doom3 sounds different now, can you try if **Vanilla** Doom3 sounds like you expect it to if you disable OpenAL in it (enter `s_useOpenAL 0` in the console and restart the game)?

**Comment by jyudoki** [comment] 2020-11-16 01:39
Just tried original Doom 3 with Open AL off and it sounds the same. The video I linked above and the Xbox version both sound a lot beefier however, with not only louder weapon sounds (chaingun being main example), but also better mixing and separation when it comes to other sounds. For example in Dhewm3 and Doom 3 PC, the chaingun sound is completely drowned out when there are imps screeching or attacking, which doesn't appear to be the case on the Xbox version.

Here's a playthrough of the Xbox version which highlights the differences:

https://www.youtube.com/watch?v=f3RACpyfOxw&list=PLIf3-4jwpiyvXUIFI5TblBWHnrDJHApum&index=11

**Comment by DanielGibson** [comment] 2021-06-03 16:19
As I wrote in #355, dhewm3 sounds (pretty much) like original Doom3 which is intended, if you want it  to sound like XBox Doom3 then creating a Mod (with modified sounds or maybe just sound shaders) would be the way to go.

**Comment by itaranto** [comment] 2022-12-27 20:32
> As I wrote in #355, dhewm3 sounds (pretty much) like original Doom3 which is intended, if you want it to sound like XBox Doom3 then creating a Mod (with modified sounds or maybe just sound shaders) would be the way to go.

I've just tried the original Doom 3 (1.3.1), and the Chaingun (for example) sounds OK there. While with dhewm3 it sounds lower than the Pistol, Shotgun or Machinegun. 

Also, weapons  like the Machinegun sounds slightly different, I have no idea why, I tested with a clean config on both cases, no mods. In both cases EAX was disabled.

**Comment by DanielGibson** [comment] 2022-12-27 20:46
Are you using the latest version of dhewm3?

Apart from that: Differences are likely due to using OpenAL vs using Doom3's integrated software audio mixer (that has been removed in dhewm3). Or did you try with OpenAL in Doom3 1.3.1 (while using EAX is only possible with OpenAL, using OpenAL should also be possible with EAX disabled).

**Comment by itaranto** [comment] 2022-12-27 21:09
> Are you using the latest version of dhewm3?

Yes, `dhewm3 1.5.2.1305` according to the logs.

> Apart from that: Differences are likely due to using OpenAL vs using Doom3's integrated software audio mixer (that has been removed in dhewm3). Or did you try with OpenAL in Doom3 1.3.1 (while using EAX is only possible with OpenAL, using OpenAL should also be possible with EAX disabled).

I used the default config which I presume it has OpenAL enabled?

I disabled EAX trough the UI and also tested with `s_useOpenAL 0` in `DoomConfig.cfg` with no noticeable change.

I used the AUR [package](https://aur.archlinux.org/packages/doom3-bin) to install the original Doom 3 1.3.1.

**Comment by DanielGibson** [comment] 2022-12-27 21:24
Original Doom3 only supported OpenAL on Windows, so you'd have to use that for comparison :-/

Doom3 for Linux used the aforementioned software mixer, dhewm3 only supports OpenAL (the Doom3 OpenAL backend has been modified extensively to support all platforms and to support "EAX effects" via EFX, which openal-soft provides on all platforms)

This issue sounds a bit like #179, but that was already resolved in 1.5.0

**Comment by itaranto** [comment] 2022-12-27 21:34
> Original Doom3 only supported OpenAL on Windows, so you'd have to use that for comparison :-/

Would it help if I test the original Doom 3 1.3.1 on Windows? 

> This issue sounds a bit like https://github.com/dhewm/dhewm3/issues/179, but that was already resolved in 1.5.0 

OK, but this seems to affect certain guns only.

**Comment by DanielGibson** [comment] 2022-12-28 00:51
> Would it help if I test the original Doom 3 1.3.1 on Windows?

Yes: Comparing OpenAL and the "classic" software sound backend on Doom3 1.3.1 on Windows would help - if OpenAL sounds the same as it does with dhewm3, then we know that it's not a regression in dhewm3. If it sounds the same as the software sound backend, that'd give us a starting point to look for the problem

> OK, but this seems to affect certain guns only.

it was the same back then (but for different weapons): it only happened when lots of loud noises were played at the same time, like when shooting with the shotgun at a metal wall thats nearby (=> apart from the shot itself there are loud impact sounds from each pellet)

**Comment by itaranto** [comment] 2022-12-28 02:07
> Yes: Comparing OpenAL and the "classic" software sound backend on Doom3 1.3.1 on Windows would help - if OpenAL sounds the same as it does with dhewm3, then we know that it's not a regression in dhewm3. If it sounds the same as the software sound backend, that'd give us a starting point to look for the problem

So I installed the Steam version of the original Doom 3 (1.3.1). This version doesn't come with OpenAL, so I copied dhewm3's `OpenAL32.dll` and placed it in `C:\Program Files (x86)\Steam\steamapps\common\Doom 3`. I made sure `seta s_useOpenAL "1"` is set in `DoomConfig.cfg`. The game had already `seta s_libOpenAL "openal32.dll"` set by default.

The weapons' volumes are correct both with and without OpenAL, I'm pretty sure it's using OpenAL because I remember seeing some log in the game's console complaining about the missing DLL which disappeared after copying the DLL.

At least I can identify the Chaingun and the Rocket Launcher as the "bad" ones, I cannot say much about the others.

**Comment by itaranto** [comment] 2022-12-28 02:09
Oh,  and BTW, the bug happens also on Windows, I've tested dhewm3 on Windows and it's the same as Linux.

**Comment by itaranto** [comment] 2022-12-28 04:35
> One more little thing: Did you make sure that OpenAL was used when s_useOpenal "1" was set?

![image](https://user-images.githubusercontent.com/11463919/209757886-599dfad8-14f1-41c2-9e1a-bdbcb03a6454.png)

**Comment by DanielGibson** [comment] 2022-12-28 05:21
Awesome, thanks!

So we know that neither OpenAL in general nor OpenAL Soft specifically is to blame (because Doom3 1.3.1 works even with OpenAL Soft), but some change in dhewm3 must be responsible for the Chaingun and Rocket Launcher having lower volume than the Pistol, Shotgun or Machine Gun.
Oh, and EAX/EFX are not involved.

**Comment by mirh** [comment] 2022-12-28 12:09
Is this related to https://github.com/LAGonauta/RetroArch/commit/3d0893a418cc83af9f9ac8c542e7422c8175d8eb#commitcomment-78380219?

**Comment by DanielGibson** [comment] 2022-12-28 18:11
Yes, good guess! :)

I think the problem here is, that in `sound/weapons.sndshd` `player_machinegun_fire` has a volume of 14dB (decibels) defined, while `player_chaingun_fire` only has a volume of 3dB.
The decibels are converted to scalar values with `idSoundSystemLocal::dB2Scale( volume )` which basically returns `pow(2.0f, volume/6.0)` - so the "initial volume" *(before things like global volume or my "scale down volume hack" from https://github.com/DanielGibson/dhewm3/commit/9261f22fa9167e487a6dbd7b6de30f9e0b2903a6 that's mentioned in the post you linked get applied)* for `player_machinegun_fire` is `5.039685` and for `player_chaingun_fire` it's `1.414214`. So *theoretically* the machinegun should be played at 3.5 times the volume of the chaingun, according to the sound shader.

**Without my hack** (if the global sound is at its default value of 0db or scalar factor 1.0), those are the values  that are then used to set AL_GAIN (OpenAL's per sound-source volume) - or rather, what's *actually* done is `alSourcef( chan->openalSource, AL_GAIN, ( volume ) < ( 1.0f ) ? ( volume ) : ( 1.0f ) );`, so **those values are clamped to 1.0** (which makes sense, because AL_GAIN only supports values between 0.0 and 1.0).
So even though `player_machinegun_fire` and `player_chaingun_fire` have pretty different volumes set in the sound shader, **in the end volume `1.0` is set as AL_GAIN for both sounds**.

However, **when using my hack** (which divides the volume by 3), the volume used for AL_GAIN is **`0.470933`** for the chaingun and `1.678215` (actually clamped to 1.0) for the machinegun. So the machinegun has twice the volume (AL_GAIN) of the chaingun - while before, due to clamping, both used 1.0 for AL_GAIN.

**Comment by DanielGibson** [comment] 2022-12-28 19:49
The solution is probably to
1. Do "my hack" (`volume *= 0.333f;`) after all other modifications of `volume` are done
2. Clamp `volume` to `1.0f` *before* that hack

Then the resulting sound mix *should* be like it was in 1.3.1 (or in dhewm3 before 1.5.0).

I've implemented this in this branch: https://github.com/dhewm/dhewm3/tree/fix-weapon-volume-issues 
Can you test it? :)

**Comment by DanielGibson** [comment] 2022-12-29 03:45
BTW, I added compiling instructions to the README.md in the same branch (they're for Debian/Ubuntu, but most of the steps are universal), hope that helps :)

**Comment by Kappa971** [comment] 2022-12-29 17:13
Visual Studio 2022 build for testing: [dhewm3-fix-volume-issues.zip](https://github.com/dhewm/dhewm3/files/10320672/dhewm3-fix-volume-issues.zip)

**Comment by itaranto** [comment] 2022-12-29 23:32
> BTW, I added compiling instructions to the README.md in the same branch (they're for Debian/Ubuntu, but most of the steps are universal), hope that helps :)

I tested it on Arch Linux using the [AUR package](https://aur.archlinux.org/packages/dhewm3-git) with the following modification:

```diff
diff --git a/PKGBUILD b/PKGBUILD
index fa2c03a..4c0b8f2 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -2,7 +2,7 @@
 # Contributor: Mike Swanson <mikeonthecomputer@gmail.com>
 _pkgname=dhewm3
 pkgname=$_pkgname-git
-pkgver=1.5.2.r1.gcc0f49f
+pkgver=1.5.2.r8.g2ec34d9
 pkgrel=1
 epoch=1
 pkgdesc="Doom 3 source port"
@@ -14,7 +14,7 @@ makedepends=('cmake' 'curl' 'git' 'libbacktrace' 'openal')
 optdepends=('doom3-data: for game data')
 provides=("$_pkgname")
 conflicts=("$_pkgname")
-source=("$_pkgname::git+https://github.com/dhewm/dhewm3.git")
+source=("$_pkgname::git+https://github.com/dhewm/dhewm3.git#branch=fix-weapon-volume-issues")
 b2sums=('SKIP')

 pkgver() {
 ```
 
 But the problem persists.

**Comment by itaranto** [comment] 2022-12-29 23:34
Oh, I see you added a bunch of other commits, particularly [this one](https://github.com/dhewm/dhewm3/commit/c8321ddd1ffa4ea3fea351a362ad091201348bd9).

I'll test it later...

**Comment by itaranto** [comment] 2022-12-30 00:12
> Visual Studio 2022 build for testing: [dhewm3-fix-volume-issues.zip](https://github.com/dhewm/dhewm3/files/10320672/dhewm3-fix-volume-issues.zip)

OK, I tested this on Windows and it works, the weapons like the pistol, shotgun, machinegun and chaingun seem to be at the same volume now.

I seems I'm doing something wrong when compiling for Linux, I'll try to fix that.

**Comment by itaranto** [comment] 2022-12-30 00:37
Well... this is very strange.

When I first tested this issue, I removed all mods and restored the config to the defaults.
But after that, I installed [D3HDP - Doom 3 Essential HD Pack v2.0](https://www.moddb.com/mods/d3hdp-doom-3-essential-hd-pack) because I actually wanted to play the game.

So I was basically testing the `fix-weapon-volume-issues` with the D3HDP enabled, so I removed the mod (and also regenerated the config from scratch and the fix seem to be working now.

I don't know what a heck is happening here. This is the *only* mod I'm using and according to its documentation, the only sound change they did (by default) was to replace the shotgun's sound with the BFG one.

**Comment by DanielGibson** [comment] 2022-12-30 02:29
> I seems I'm doing something wrong when compiling for Linux, I'll try to fix that.

Just compile manually, like described in the README of that branch.
(The first step might not be directly applicable for your distro, but as you've compiled dhewm3 via AUR, you should already have the dependencies installed and can skip that step)

**Comment by itaranto** [comment] 2022-12-30 02:42
> Just compile manually, like described in the README of that branch. (The first step might not be directly applicable for your distro, but as you've compiled dhewm3 via AUR, you should already have the dependencies installed and can skip that step)

See my previous comment, I was actuallycompiling correctly, it was the D3HDP mod causing the issue. I double, triple checked and it seems the mod is causing the volume issue even when using the  `fix-weapon-volume-issues` build.

Without the mod, dhewm3 1.5.2 has the volume issue and the `fix-weapon-volume-issues` build fixes it.

For some reason, D3HDP is somehow bringing the issue back, I checked the .pk4 files, particularly the file `weapons.sndshd`: the `volume` values in the mod's .pk4 file (`zzz_pak005.pk4`), are the same as the base one (`pak005.pk4`).

**Comment by DanielGibson** [comment] 2022-12-30 02:53
That's weird.
Is the global volume setting (that slider in the menu) different when the mod is installed?
(Maybe it ships a config that sets `s_volume_dB`)

>  the only sound change they did (by default) was to replace the shotgun's sound with the BFG one.

Looking at their zzz_pak005.pk4, they also replaced the pistol soundfiles and changed the `player_pistol_fire` volume from 13 to 0

**Comment by itaranto** [comment] 2022-12-30 03:02
> That's weird. Is the global volume setting (that slider in the menu) different when the mod is installed? (Maybe it ships a config that sets `s_volume_dB`)

I checked that in fact and `s_volume_dB` and it's the same in both cases: `seta s_volume_dB "0"`.

> Looking at their zzz_pak005.pk4, they also replaced the pistol soundfiles and changed the `player_pistol_fire` volume from 13 to 0

Yeah, I missed that, I just made a `diff` of the two and that seems to be the only volume-related change.

I'm just trying to make sure if this is an engine/executable bug or a mod's bug.

**Comment by DanielGibson** [comment] 2022-12-30 03:04
I don't know how you tested, but if you only test with machinegun and chaingun (and ignore pistol and shotgun), at least those of their changes we already identified shouldn't make a difference

**Comment by itaranto** [comment] 2022-12-30 03:14
> I don't know how you tested, but if you only test with machinegun and chaingun (and ignore pistol and shotgun), at least those of their changes we already identified shouldn't make a difference

The machinegun is higher volume than the chaingun when the D3HDP is installed even with the `fix-weapon-volume-issues`.

Again, I don't want to blame you guys for this, I just thought it could be uncovering some hidden weird edge case.

From what I understand this mod only changes the volume for the pistol *but* it also uses different .wav files for the pistol, shotgun and machinegun. Maybe those .wav files are higher volume.

This is likely the mod's issue I would say, but I'm not 100% sure.

**Comment by DanielGibson** [comment] 2022-12-30 03:24
> This is likely the mod's issue I would say.

That would be my assumption as well.
Does D3HDP behave the same in Doom3 1.3.1?

**Comment by itaranto** [comment] 2022-12-30 04:40
> That would be my assumption as well. Does D3HDP behave the same in Doom3 1.3.1?

I just did, and it's the same. So it's the mod's fault.

**Comment by Kappa971** [comment] 2022-12-30 14:40
@DanielGibson the issue with cmake in Visual Studio is fixed, thanks.

**Comment by Kappa971** [comment] 2023-01-11 20:08
Hi @DanielGibson, I saw that you are also a contributor in Yamagi Quake 2 and I noticed that it has the same problem with cmake and Visual Studio.

**Comment by DanielGibson** [comment] 2023-01-16 05:03
you're right, thanks for reminding me, see https://github.com/yquake2/yquake2/pull/960

**Closed by DanielGibson** 2023-01-16 05:03 UTC
