### ISSUE TITLE
EAX reverb strength

### ISSUE THREAD

**Issue by vlad54rus** [dhewm/dhewm3#365] opened 2021-04-09 10:43 UTC
While dhewm3 provides support for EAX, some reverb zones in Doom 3 have stupidly high reverb strength. Creating alsoft.ini file with the following content reduces it to a more acceptable levels:
```
[reverb]
boost=-7
```
Can you consider supplying this file with the release builds?

**Comment by dezo2** [comment] 2021-04-11 12:56
Thanks for the tip, I didn't know this can be adjusted using local ini file.
The default amount of reverb is indeed ridiculous.

**Comment by DanielGibson** [comment] 2021-04-12 05:06
I'll try to create a cvar to set this, apparently something similar to that boost setting can be done with `alAuxiliaryEffectslotf(slot, AL_EFFECTSLOT_GAIN, gain);` where gain is a value between 0 and 1 (1 by default; `0.5` should be similar to `boost=-7`).

I was also told that there's openal warnings when quitting the game (when setting env var `ALSOFT_LOGLEVEL=2` or 3 when starting the game) about effect slots being deleted while there's still sources attached to them - most probably because `idSoundWorldLocal::Shutdown() ` first deletes the `listenerSlot` and later the `emitters` which contain the sources.

**Comment by DanielGibson** [comment] 2021-04-12 18:43
Hi, can you test if the build linked in https://github.com/dhewm/dhewm3/pull/363#issuecomment-818039817 fixes your issues?
Remove the boost setting from your `alsoft.ini` and in dhewm3 set the `s_alReverbGain` to `0.5` or whatever sounds best for you:
Open the console (Shift+Esc), enter `s_alReverbGain 0.5`.

(In case you're not using Windows, check out this branch and compile dhewm3 yourself: https://github.com/DanielGibson/dhewm3/tree/reduce-dependencies)

**Comment by nbohr1more** [comment] 2021-04-13 03:32
I locally merged this into The Dark Mod but it doesn't seem to have any affect.
We may have a few local deviations that break compatibility.

That said, when I began looking into this I found that the master volume for all EFX definitions is controlled by the "room" parameter. My plan was to hook into whichever branch accepts that parameter.

**Comment by DanielGibson** [comment] 2021-04-13 03:56
No idea about TDM, but in dhewm3 `s_alReverbGain 0.5` definitely makes a noticeable difference, 0.1 or 0.0 even more so, of course (*if EAX is enabled*; 0.0 sounds like when it's disabled).

The "room" parameter sets reverb gain (`AL_EAXREVERB_GAIN`) for the current area, I think setting `AL_EFFECTSLOT_GAIN` on the slot should have about the same effect, but for everything that uses the slot (theres one `listenerSlot` per soundworld, and two soundworlds: one for the menu and one for ingame).
I think setting it on the slot is the cleanest way to do it if you want a global setting, otherwise you'll have to
1. set it for all effects (and change it if the cvar changes!)
2. keep ugly special cases in mind, like "what if the .efx file doesn't set `room` at all?"

No idea why it doesn't seem to work in TDM, maybe you have more such slots or you just didn't have EAX effects enabled or whatever; it's probably worth debugging

**Comment by nbohr1more** [comment] 2021-04-13 04:05
I agree that the slot approach is the best, I really don't want to do this junk:

else if ( token == "room" ) {
			efxf(AL_EAXREVERB_GAIN, mB_to_gain( (src.ParseInt() * tdm_offset_junk_int ) , GAIN));

but it should work...

The change takes effect in real-time right ?
The setting also overrides alsoft.ini ?

**Comment by DanielGibson** [comment] 2021-04-13 04:11
> `(src.ParseInt() * tdm_offset_junk_int `

you don't want to make it an int but a float, otherwise it can't decrease the value (only to 0) and I have no idea what any number even means there, like, is 0.5 half as strong or what? after all, DB is logarithmic..

> The change takes effect in real-time right ?

if you do it my way: yes. if you do it your way: no (the EFX files aren't re-parsed all the time)

> The setting also overrides alsoft.ini ?
no, as far as I understand the `[reverb] boost=..` setting in alsoft.ini is applied globally on top of whatever gains are set in the applications, like an additional factor or whatever

**Comment by vlad54rus** [comment] 2021-04-13 08:29
On the new build EAX is buggy - any changes in EAX zones and cvars only apply when i hit ESC button.

**Comment by DanielGibson** [comment] 2021-04-13 15:46
> On the new build EAX is buggy - any changes in EAX zones and cvars only apply when i hit ESC button.

interesting. hmm.. might be caused by https://github.com/dhewm/dhewm3/commit/13ac657ebfb4ab4ef5850b802d75a03b447d8bf0 (but then the code was already pretty broken before and just worked accidentally)

**Comment by DanielGibson** [comment] 2021-04-13 20:20
Hmm seems like this problem only happens in new(er?) versions of OpenAL - 1.21.1 (which is bundled with that test build) has it, 1.19.1 (which was bundled with the official 1.5.**0** release binaries) doesn't. 
I'll have to investigate.

**Comment by DanielGibson** [comment] 2021-04-13 22:56
Ok, this is a bug in openal-soft, their maintainer already found out what causes it.

I'll likely implement a workaround in dhewm3 to make sure this bug won't turn up in linux distros shipping affected openal-soft versions

**Comment by DanielGibson** [comment] 2021-04-14 03:19
https://github.com/dhewm/dhewm3/pull/363#issuecomment-819199093 has a new testbuild that should fix the issue by working around the openal bug (and, TBH, the code is better now)

**Comment by nbohr1more** [comment] 2021-04-14 04:00
We have some divergences but I was able to merge this and get the feature working! THANK YOU!!!

**Comment by DanielGibson** [comment] 2021-04-14 04:10
awesome!

**Comment by vlad54rus** [comment] 2021-04-14 08:59
Works great, thank you.
Maybe make 0.5 the default value?

**Comment by dezo2** [comment] 2021-04-14 23:19
The new cvar for reverb works perfect, but now all looped ambient "music" stops after a few seconds of playing.

**Comment by DanielGibson** [comment] 2021-04-15 07:48
> Maybe make 0.5 the default value?

hmm, maybe, I'll think about it 

> now all looped ambient "music" stops after a few seconds of playing.

thanks for reporting (and for including a savegame!), I'll look into that - at least short loops seemed to work when I tested, but sound files longer than 6 seconds or so are handled differently. most probably this is related to the switch to stb_vorbis, but we'll see.

**Comment by DanielGibson** [comment] 2021-04-24 05:17
@dezo2: Somehow your savegame doesn't load properly ("WARNING: Real Script checksum didn't match the one from the savegame!"), maybe you have some mod with its own scripts installed in base/?

Could you just post a screenshot of the right place to hear the sound?

**Comment by DanielGibson** [comment] 2021-04-24 15:21
Ok, I found the place and fixed the bug, I'll post updated Win32 binaries later

**Comment by DanielGibson** [comment] 2021-04-24 17:41
Here's new Windows binaries with all the changes of that branch including the latest fix for the looping sound issue, can you test if it works for you? Thanks! :)
[dhewm3-1.5.2pre-win32-reduce-deps-fixed.zip](https://github.com/dhewm/dhewm3/files/6370243/dhewm3-1.5.2pre-win32-reduce-deps-fixed.zip)

**Comment by dezo2** [comment] 2021-04-24 18:41
Hi Daniel, I tried multiple levels with this pre-release and all looped sounds are working again.
Thank you for fixing!
PS: The save was from clean 1.5.1 (no mods) - all older saves will cause this warning I think.

**Comment by DanielGibson** [comment] 2021-04-24 22:17
That's good to hear, thanks a lot for testing!

Weird that the savegame didn't work though.

**Closed** 2021-04-27 18:09 UTC

**Comment by DanielGibson** [comment] 2021-04-27 19:56
It's all in master now, `s_alReverbGain` now defaults to `0.5`
