### ISSUE TITLE
Performance regression with dhewm3 1.5.4 + Librecoop 1.5 Alpha 

### ISSUE THREAD

**Issue by gut5** [dhewm/dhewm3#606] opened 2024-08-09 18:28 UTC
Experiencing a drop to around 15-30FPS when playing Librecoop. with one other person. Other times the game runs at a stable 60FPS. 
I can add further info if needed.

[dhewm3log.txt](https://github.com/user-attachments/files/16565549/dhewm3log.txt)

edit: I've tested this by creating a Librecoop multiplayer server through the game UI and without even having another player join. It doesn't get any worse if someone joins though. Also tested by creating a standard multiplayer Tourney game (i.e. nothing to do with Librecoop) server and just walking around and the FPS stays at around 60FPS. So it's just happening to Librecoop.

**Comment by DanielGibson** [comment] 2024-09-10 12:01
duplicate of #614

**Closed by DanielGibson** 2024-09-10 12:01 UTC
