### ISSUE TITLE
All models stuck in T-Pose on PowerMac G5 

### ISSUE THREAD

**Issue by Astal4** [dhewm/dhewm3#472] opened 2022-07-07 21:54 UTC
Hello! I've got a PowerMac G5 Quad that I'm playing with, it's running Gentoo, and on the X1900 GT, all models are stuck in a T-Pose. It's a funny glitch, but still a glitch. 

Built with `-Ofast` and `-maltivec`, this is from the stable release.
![image](https://user-images.githubusercontent.com/105772205/177877819-d3c57169-e776-438b-a3c3-2c27b83a4a8b.png)

**Comment by GnollAstal** [comment] 2022-07-08 00:28
Retrying with -O2 -maltivec instead

**Comment by GnollAstal** [comment] 2022-07-08 00:39
No difference. still issues with `-O2`

**Comment by Cowcat5150** [comment] 2022-07-24 09:49
Depending of the PPC system, altivec doesn't work as it is from those old sources.

I've tested some altivec for MorphOS platform (G4), and one of the functions that does funny things with models is BlendJoints: Try to copy paste the SIMD_Generic version equivalent to the SIMD_Altivec source.

Or try to compile a version that only uses Generic Simd code.

**Comment by FuryOusFrank** [comment] 2022-10-24 23:24
Hi. Same problem with a Quad G5 running Void ppc64. I replaced the whole SIMD_Altivec.cpp file for SIMD_generic and all the models are still stuck with the T-Pose. I can't interact with them either. Was a solution ever found?

**Comment by DanielGibson** [comment] 2024-10-31 02:14
This problem should be fixed in the following branch: https://github.com/DanielGibson/dhewm3/tree/fix-ppc64be

@Astal4 @FuryOusFrank could you please test that branch to see if it works for you, and to make sure there are not additional 64bit Big Endian problems we haven't found yet?
Thanks in advance! :)

**Comment by DanielGibson** [comment] 2024-10-31 02:23
See also #626

**Comment by FuryOusFrank** [comment] 2024-10-31 12:27
> @Astal4 @FuryOusFrank could you please test that branch to see if it works for you, and to make sure there are no additional 64bit Big Endian problems we haven't found yet?
> Thanks in advance! :)

Thanks! My G5 is not working at this time. Overheating caused by the age of the liquid cooling system. I'll look into it as soon as I can.

**Comment by DanielGibson** [comment] 2024-11-07 13:55
fix merged

**Closed by DanielGibson** 2024-11-07 13:55 UTC
